server.port: 8082

security:
  basic:
    enabled: false

spring:
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/movies?useSSL=false
    username: root
    password: Password


logging.level:
  root: WARN
  org.superbiz.moviefun: DEBUG
